# AVALIAÇÃO #

# CRIAR UM DOCUMENTO HTML EM QUARTO
# ISTO É, UMA PAGINA DE INTERNET COM SEUS GRÁFICOS

# PRIMEIRO PASSO
# INSTALAR O PACOTE QUARTO
#install.packages('quarto')
library(quarto)

# 2° PASSO
#PARA ABRIR A PÁGINA CLICAR EM "RENDER"

#EDITAR O ARQUVO
#ALTERAR O TITULO PARA O SEU NOME
# ALTERAR O TITULO (title) PARA O SEU NOME
# MODIFICAR A PARTE (R chunk) DAS BIBLOTECAS
# ADICIONAR O CARREGAMENTO DOS DADOS